version: "3.9"
services:
  indomie:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      BOTLOG_CHATID: $BOTLOG_CHATID
      STRING: $STRING
      API_KEY: $API_KEY
      API_HASH: $API_HASH
